---

- set_fact:
    automysqlbackup_config_file: "{{ etc_prefix }}/etc/automysqlbackup/local.conf"

- set_fact:
    automysqlbackup_DBEXCLUDE: "('information_schema' 'lost+found' 'performance_schema')"
  when: automysqlbackup_DBEXCLUDE is not defined

- name: Ensure no installed automysqlbackup package
  package:
    name: automysqlbackup
    state: absent

- name: Copy automysqlbackup
  copy:
    src: 3.0/automysqlbackup
    dest: /usr/local/bin/
    mode: 0755

- name: Copy automysqlbackup-cron
  template:
    src: 3.0/automysqlbackup-cron
    dest: /usr/local/bin/
    mode: 0755

- name: "Create {{ etc_prefix }}/etc/automysqlbackup/"
  file:
    path: "{{ etc_prefix }}/etc/automysqlbackup/"
    state: directory

- name: Copy automysqlbackup config file
  copy:
    src: 3.0/automysqlbackup.conf.sample
    dest: "{{ etc_prefix }}/etc/automysqlbackup/"

- name: "Create {{ automysqlbackup_config_file }}"
  copy:
    content: ""
    dest: "{{ automysqlbackup_config_file }}"
    force: no
    mode: 0640

- name: Set BACKUPDIR
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: "CONFIG_backup_dir="
    line: "CONFIG_backup_dir='{{ automysqlbackup_BACKUPDIR }}'"
    create: yes
  when: automysqlbackup_BACKUPDIR is defined

- name: Set DBEXCLUDE
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: CONFIG_db_exclude=
    line: "CONFIG_db_exclude={{ automysqlbackup_DBEXCLUDE }}"

- name: Set DOWEEKLY
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: CONFIG_do_weekly=
    line: "CONFIG_do_weekly='{{ automysqlbackup_DOWEEKLY }}'"
  when: automysqlbackup_DOWEEKLY is defined

- name: Set MAILADDR
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: CONFIG_mail_address=
    line: "CONFIG_mail_address='{{ automysqlbackup_MAILADDR }}'"
  when: automysqlbackup_MAILADDR is defined

- name: Set MAILCONTENT
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: CONFIG_mailcontent=
    line: "CONFIG_mailcontent='{{ automysqlbackup_MAILCONTENT|default('quiet') }}'"

- name: Set MAX_ALLOWED_PACKET
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: CONFIG_mysql_dump_max_allowed_packet=
    line: "CONFIG_mysql_dump_max_allowed_packet='{{ automysqlbackup_MAX_ALLOWED_PACKET }}'"
  when: automysqlbackup_MAX_ALLOWED_PACKET is defined

- name: Set MDBNAMES
  lineinfile:
    dest: "{{ automysqlbackup_config_file }}"
    regexp: CONFIG_db_month_names=
    line: "CONFIG_db_month_names={{ automysqlbackup_MDBNAMES }}"
  when: automysqlbackup_MDBNAMES is defined

# cron executes at 0:30 and not "daily" as we want it before MIT-Backup
# FreeBSD support /usr/local/etc/cron.d, but it does not exists by default (13.2)
- name: Add cron.d script
  template:
    src: 3.0/etc/cron.d/local-automysqlbackup
    dest: "{{ etc_prefix }}/etc/cron.d/"

- name: Add cron.daily script local-automysqlbackup-cleanup
  copy:
    src: 3.0/local-automysqlbackup-cleanup
    dest: "{{ cron_daily }}local-automysqlbackup-cleanup"
    mode: 0755

