---

- name: Ensure no local install of automysqlbackup
  file: path={{ item }} state=absent
  with_items:
    - /etc/automysqlbackup/automysqlbackup.conf
    - /etc/automysqlbackup/README
    - /etc/automysqlbackup/LICENSE
    - /etc/cron.daily/mysqlbackup
    - /usr/local/bin/automysqlbackup

- name: "Ensure automysqlbackup is installed"
  apt: pkg=automysqlbackup

- name: Ensure CREATE_DATABASE=no in automysqlbackup config
  lineinfile: dest=/etc/default/automysqlbackup regexp='CREATE_DATABASE=' line='CREATE_DATABASE=no'

- name: Set BACKUPDIR
  lineinfile:
    dest: /etc/default/automysqlbackup
    regexp: 'BACKUPDIR='
    line: 'BACKUPDIR="{{ automysqlbackup_BACKUPDIR }}"'
  when: automysqlbackup_BACKUPDIR is defined

- name: Set DBEXCLUDE
  lineinfile:
    dest: /etc/default/automysqlbackup
    regexp: 'DBEXCLUDE='
    line: "DBEXCLUDE=\"{{ automysqlbackup_DBEXCLUDE|default('information_schema lost+found performance_schema') }}\""
#  when: automysqlbackup_DBEXCLUDE is defined

- name: Set DOWEEKLY
  lineinfile:
    dest: /etc/default/automysqlbackup
    regexp: 'DOWEEKLY='
    line: 'DOWEEKLY="{{ automysqlbackup_DOWEEKLY }}"'
  when: automysqlbackup_DOWEEKLY is defined

- name: Set MAILADDR
  lineinfile:
    dest: /etc/default/automysqlbackup
    regexp: 'MAILADDR='
    line: 'MAILADDR="{{ automysqlbackup_MAILADDR }}"'
  when: automysqlbackup_MAILADDR is defined

- name: Set MAX_ALLOWED_PACKET
  lineinfile:
    dest: /etc/default/automysqlbackup
    regexp: 'MAX_ALLOWED_PACKET='
    line: 'MAX_ALLOWED_PACKET="{{ automysqlbackup_MAX_ALLOWED_PACKET }}"'
  when: automysqlbackup_MAX_ALLOWED_PACKET is defined

- name: Set MDBNAMES
  lineinfile: dest=/etc/default/automysqlbackup regexp='MDBNAMES=' line='MDBNAMES="{{ automysqlbackup_MDBNAMES }}"'
  when: automysqlbackup_MDBNAMES is defined

- name: Add mysqldump options for event-table to /etc/mysql/debian.cnf (1/3)
  ini_file:
    dest: /etc/mysql/debian.cnf
    section: mysqldump
    option: ignore-table
    value: mysql.events

- name: Add mysqldump options for event-table to /etc/mysql/debian.cnf (2/3)
  lineinfile:   
    dest: /etc/mysql/debian.cnf
    regexp: '^events$'
    line: 'events'
    insertbefore: '^ignore-table'

- name: Add mysqldump options for event-table to /etc/mysql/debian.cnf (3/3)
  lineinfile:
    dest: /etc/mysql/debian.cnf
    regexp: '^# events parameter added by ansible role mit.automysqlbackup$'
    line:    '# events parameter added by ansible role mit.automysqlbackup'
    insertbefore: '^\[mysqldump\]$'

- name: Add cron.daily script local-automysqlbackup-cleanup
  copy: src=local-automysqlbackup-cleanup dest=/etc/cron.daily/local-automysqlbackup-cleanup mode=0755

# We disable the default mysql script at /etc/cron.daily/automysqlbackup. 
# This might lead to problems while upgrading, and we could do two backups every.
# The second backup removes the first on the disk. But as of 2020-02-01 the second
# weeky and monthly backup will not be removed and this is not acceptable.
# find weekly monthly -name "*06h25m*gz" -delete

- name: Add cron.d script to do automysqlbackup before MIT-Backup
  copy:
    src: cron.d-local-automysqlbackup
    dest: /etc/cron.d/local-automysqlbackup
  when: mit_backup == True
- name: Disable the default automysqlbackup at cron.daily
  lineinfile:
    dest: /etc/cron.daily/automysqlbackup
    regexp: "^/usr/sbin/automysqlbackup"
    line:   "# disabled-by-mit.automysqlbackup /usr/sbin/automysqlbackup"
  when: mit_backup == True

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Logcheck rules
  copy:
    src: logcheck-mit-defaults-automysqlbackup
    dest: /etc/logcheck/ignore.d.server/mit-defaults-automysqlbackup
  when: "'logcheck' in ansible_facts.packages"

