#!/bin/sh
#
# Distributed via ansible - mit.automysqlbackup

PATH=${PATH}:/usr/local/bin
for conf in $(ls {{ etc_prefix }}/etc/automysqlbackup/*.conf); do
    automysqlbackup -c ${conf} -b 1>/dev/null
done

