#!/usr/bin/env sh
#
# Distributed via ansible - mit.automysqlbackup
#
# v2024-04-29-1

for conf in $(ls {{ etc_prefix }}/etc/automysqlbackup/*.conf); do
    CONFIG_backup_dir="$(egrep '^CONFIG_backup_dir=' $conf | cut -d= -f2-)"
    if [ -d "$CONFIG_backup_dir" ]; then
        # Delete all backups older than 365 days
        find $CONFIG_backup_dir -type f \( -name "*.sql.gz" -o -name "*.sql.bz2" \) -mtime +365 \
            -exec rm -v {} \; | logger -t $0
    else
        echo "BACKUPDIR=$CONFIG_backup_dir is not a directory!"
    fi
done

