#!/usr/bin/env bash
#
# Distributed via ansible - mit.automysqlbackup
#
# v2021-10-12-1

for conf in $(ls /etc/automysqlbackup/*.conf); do
    . ${conf}
    if [ -d "${CONFIG_backup_dir}" ]; then
        # Delete all backups older than 365 days
        find ${CONFIG_backup_dir} -type f \( -name "*.sql.gz" -o -name "*.sql.bz2" \) -mtime +365 \
            -exec rm -v {} \; | logger -t $0
    else
        echo "BACKUPDIR=${CONFIG_backup_dir} is not a directory!"
    fi
done

